# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 531fcde67e1d58e660c4d4e12a5c484abc56a45b5998d9ed625d6106c523ace52b66742e4b23b62052085dcf992fb8e9d0c81870ec5b99c70870b1cc05f9513f

test:
  secret_key_base: fe9d88ef16f7800450d1fb8371168237f8abec3fd92012b158bbb6f1820be98fb55fd2d83f67b5fdaba7c66fdccecc51687dba37c66295bd0758242d4d5c4fc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
